# StyLua configuration for Morphomatic

indent_type = "Spaces"
indent_width = 2
column_width = 100
line_endings = "Unix"

quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Always"

space_after_function_names = "Never"
