name: Lint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Lua
        uses: leafo/gh-actions-lua@6919171ccf181b826f44b9bca76307b577217377 # v13
        with:
          luaVersion: "5.4"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@97053c556d6ce2c8e26eb7ac93743437c7af7248 # v6

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: luacheck .
