name: Package & Upload (CurseForge)

on:
  push:
    tags:
      - "v*.*.*"   # ex: v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # packager lit les tags/commits

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Run BigWigs Packager
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        with:
          args: -g retail
